baseURL: 'https://assayire.github.io'
title: Assayire's Den of Tricks
theme: coder # Other: https://chesterhow.github.io/tale/ 

languageCode: en
defaultContentLanguage: en
enableEmoji: true

paginate: 20
pygmentsStyle: colorful # https://xyproto.github.io/splash/docs/
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
enableEmoji: true
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  # author: Assayire
  description: Assayire's personal website
  keywords: 'blog,developer,personal'
  # info:
  #   - Full Stack DevOps
  #   - Musician
  avatarURL: images/avatar.jpg
  dateFormat: 'January 2, 2006'
  since: 2019
  commit: 'https://github.com/luizdepra/hugo-coder/tree/'
  rtl: false
  colorScheme: auto
  hideColorSchemeToggle: false
  maxSeeAlsoItems: 5
  customCSS: []
  customSCSS: ['css/custom.scss']
  customJS: []
  csp:
    childsrc:
      - '''self'''
    fontsrc:
      - '''self'''
      - 'https://fonts.gstatic.com'
      - 'https://cdn.jsdelivr.net/'
    formaction:
      - '''self'''
    framesrc:
      - '''self'''
    imgsrc:
      - '''self'''
    objectsrc:
      - '''none'''
    stylesrc:
      - '''self'''
      - '''unsafe-inline'''
      - 'https://fonts.googleapis.com/'
      - 'https://cdn.jsdelivr.net/'
    scriptsrc:
      - '''self'''
      - '''unsafe-inline'''
      - 'https://www.google-analytics.com'
      - 'https://cdn.jsdelivr.net/'
    prefetchsrc:
      - '''self'''
    connectsrc:
      - '''self'''
      - 'https://www.google-analytics.com'
  social:
    - name: Github
      icon: fa fa-2x fa-github
      weight: 1
      url: 'https://github.com/johndoe/'
    - name: Gitlab
      icon: fa fa-2x fa-gitlab
      weight: 2
      url: 'https://gitlab.com/johndoe/'
    - name: Twitter
      icon: fa fa-2x fa-twitter
      weight: 3
      url: 'https://twitter.com/johndoe/'
    - name: LinkedIn
      icon: fa fa-2x fa-linkedin
      weight: 4
      url: 'https://www.linkedin.com/in/johndoe/'
    - name: Medium
      icon: fa fa-2x fa-medium
      weight: 5
      url: 'https://medium.com/@johndoe'
    - name: RSS
      icon: fa fa-2x fa-rss
      weight: 6
      url: 'https://myhugosite.com/index.xml'
      rel: alternate
      type: application/rss+xml
taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: About
          weight: 1
          url: about/
        - name: Blog
          weight: 2
          url: posts/
        - name: Projects
          weight: 3
          url: projects/
        - name: Contact me
          weight: 5
          url: contact/
  pt-br:
    languageName: ':brazil:'
    title: João Ninguém
    params:
      author: João Ninguém
      info: Full Stack DevOps e Mágico
      description: Sítio pessoal de João Ninguém
      keywords: 'blog,desenvolvedor,pessoal'
    menu:
      main:
        - name: Sobre
          weight: 1
          url: about/
        - name: Blog
          weight: 2
          url: posts/
        - name: Projetos
          weight: 3
          url: projects/
        - name: Contato
          weight: 5
          url: contact/
